apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  containers:
  - args:
    - "sleep"
    - "10"
    image: busybox
    name: sleep
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
