apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    workflows.argoproj.io/workflow: something
  name: bb-kfp
spec:
  containers:
  - args:
    - "sleep"
    - "10"
    image: busybox
    name: sleep
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
