apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    workflows.argoproj.io/workflow: something
  name: bb-kfp-initial
spec:
  containers:
  - args:
    - "sleep"
    - "10"
    image: busybox
    name: sleep
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    app.iguazio.com/node-group: initial
status: {}
