apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job-type: workflow-runner
  generateName: bb-wfr-
spec:
  containers:
  - args:
    - "sleep"
    - "10"
    image: busybox
    name: sleep
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
